version: "3"
services:
  db:
    image: mongo:latest
    logging:
      driver: none
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:3000
    command: npm run dev
  admin:
    build: ./cms-admin
    volumes:
      - ./cms-admin:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm start
    stdin_open: true
