version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  api:
    build: ./workspace-game-api
    volumes:
      - ./workspace-game-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - 8080:8080
    command: npm run dev
    environment:
      MONGO_URL: mongodb://db:27017/workspaceManagement
      PORT: 8080

  admin:
    build: ./cms-admin
    volumes:
      - ./cms-admin:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm start
    stdin_open: true
  web:
    build: ./cms-web
    volumes:
      - ./cms-web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:3000
    command: npm start
    stdin_open: true
